# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template
    required: false

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true
    required: false

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]
    required: false

departments:
    name: Abteilung
    slug: departments
    singular_slug: department
    behaves_like: grouping
    options:
        actors: Schauspiel
        backstage: Backstage
        technitians: Technik & Licht

play_categories:
    name: Kategorie
    slug: play_categories
    singular_slug: play_category
    behaves_like: categories
    multiple: true
    options:
        premiere: Premiere
        renewal: Wiederaufnahme
        current_season: Aktuelle Saison
        show_on_home: Auf Startseite zeigen
        archived: Archiviert

show_categories:
    name: Kategorie
    slug: show_categories
    singular_slug: show_category
    behaves_like: categories
    multiple: true
    options:
        sold_out: Ausverkauft
        premiere: Premiere
        guest_show: Gastspiel
        cancelled: Abgesagt

show_notes:
    name: Notiz
    slug: show_notes
    singular_slug: show_note
    behaves_like: tags
    multiple: false

contact_detail_categories:
    name: Anzeigen in
    slug: contact_categories
    singular_slug: contact_category
    behaves_like: categories
    multiple: true
    options:
        footer: Footer
        contact_page: Kontaktseite
        toolbar: Menüleiste

entry_categories:
    name: Anzeigen auf
    slug: entry_categories
    singular_slug: entry_categoriy
    behaves_like: categories
    multiple: true
    options:
        homepage: Homepage
        infopage: Info-Seite